binary_sensor:
  - platform: homeassistant
    id: ${low_batt_label_ico}_bin
    internal: True
    entity_id: ${low_batt_entity_id}
    publish_initial_state: True
    on_press:
      then:
        - lvgl.label.update:
            id: ${low_batt_label_ico}
            hidden: False
    on_release:
      then:
        - lvgl.label.update:
            id: ${low_batt_label_ico}
            hidden: True

sensor:
  - platform: homeassistant
    id: ${moisture_value_label}_sens
    internal: True
    entity_id: ${moisture_value_entity_id}
    on_value:
      then:
        - lvgl.label.update:
            id: ${moisture_value_label}
            text:
              format: "%.0f%%"
              args: x
# Used for meter variant widget only
#        - lvgl.indicator.update:
#            id: ${moisture_meter_needle}
#            value: !lambda return x;
# Used for arc variant widget only
        - lvgl.arc.update:
            id: ${moisture_meter_needle}
            value: !lambda return x;
            indicator:
              arc_color: !lambda |- 
                if(x > 85) { return lv_color_make(id(color_blue).red, id(color_blue).green, id(color_blue).blue); }
                else if (x < ${low_level_value}) { return lv_color_make(id(color_red).red, id(color_red).green, id(color_red).blue); }
                else { return lv_color_make(id(color_green).red, id(color_green).green, id(color_green).blue); }
