binary_sensor:
  - platform: template
    id: id_bin_bl_state
    filters:
      - delayed_off: !lambda "return ((id(id_num_bl_timeout).state - ${screen_idle_timeout_seconds}) * 1000 );"
    on_press:
      then:
        - light.turn_on: 
            id: id_light_backlight_brightness
            brightness: 100%
    on_release:
      then:
        - light.turn_on:
            id: id_light_backlight_brightness
            brightness: 20%
        - if:
            condition:
              - not:
                  - lvgl.page.is_showing: page_music
            then:
              - lvgl.tileview.select:
                  id: id_lv_tile_main
                  tile_id: id_lv_tile_page0
                  animated: true
              - lvgl.page.show: page_home
        - lvgl.pause: