binary_sensor:
  - platform: template
    id: id_template_api_status
    internal: True
    condition:
      api.connected:
    on_press:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_ha_status
            text_color: color_blue
    on_release: 
      then:
        - lvgl.label.update: 
            id: id_lv_lab_ha_status
            text_color: color_dark_gray

  # Front door from HA #
  - platform: homeassistant
    id: id_ha_front_door
    entity_id: binary_sensor.ademcointerposer_avant
    trigger_on_initial_state: True
    on_press:
      then:
        - lvgl.widget.update: 
            id: id_lv_but_front_door
            hidden: false
    on_release:
      then:
        - lvgl.widget.update: 
            id: id_lv_but_front_door
            hidden: true

  # Patio door from HA #
  - platform: homeassistant
    id: id_ha_patio_door
    entity_id: binary_sensor.ademcointerposer_patio
    trigger_on_initial_state: True
    on_press:
      then:
        - lvgl.widget.update: 
            id: id_lv_but_patio_door
            hidden: false
    on_release:
      then:
        - lvgl.widget.update: 
            id: id_lv_but_patio_door
            hidden: true

  # Miner is running from HA #
  - platform: homeassistant
    id: id_ha_mining_running
    entity_id: binary_sensor.mining_rig_est_en_fonction
    trigger_on_initial_state: True
    on_press:
      then:
        - lvgl.widget.update: 
            id: id_lv_but_miner_status
            hidden: false
    on_release:
      then:
        - lvgl.widget.update: 
            id: id_lv_but_miner_status
            hidden: true

  # Global Alert for Outside SoilSensors from HA #
  - platform: homeassistant
    id: id_ha_outside_watering_alert
    entity_id: binary_sensor.low_moisture_sensors_outside_alert
    trigger_on_initial_state: True
    on_press:
      then:
        - lvgl.widget.update: 
            id: id_lv_but_outside_soil_alert
            hidden: false
    on_release:
      then:
        - lvgl.widget.update: 
            id: id_lv_but_outside_soil_alert
            hidden: true

  # Global Alert for Inside SoilSensors from HA #
  - platform: homeassistant
    id: id_ha_inside_watering_alert
    entity_id: binary_sensor.low_moisture_sensors_inside_alert
    trigger_on_initial_state: True
    on_press:
      then:
        - lvgl.widget.update: 
            id: id_lv_but_inside_soil_alert
            hidden: false
    on_release:
      then:
        - lvgl.widget.update: 
            id: id_lv_but_inside_soil_alert
            hidden: true

  # Défi Hilo Status from HA #
  - platform: homeassistant
    id: id_ha_defi_hilo_active
    entity_id: binary_sensor.defi_hilo_thermostat_central_override_is_active
    trigger_on_initial_state: True
    on_press:
      then:
        - lvgl.widget.update: 
            id: id_lv_but_defi_hilo
            hidden: false
    on_release:
      then:
        - lvgl.widget.update: 
            id: id_lv_but_defi_hilo
            hidden: true

    # Attic light state #
  - platform: homeassistant
    id: id_attic_light
    entity_id: light.${grenier_light_ha_entity_id}
    trigger_on_initial_state: True
    on_press:
      then:
        - lvgl.widget.update: 
            id: id_lv_but_notify_attic_light
            hidden: false
        - lvgl.button.update: 
            id: id_lv_but_attic_light
            shadow_color: color_warmest_white
            shadow_spread: 3
            shadow_width: 35
        - lvgl.label.update:
            id: id_lv_lab_attic_light
            text_color: color_warmest_white
    on_release:
      then:
        - lvgl.widget.update: 
            id: id_lv_but_notify_attic_light
            hidden: true
        - lvgl.button.update: 
            id: id_lv_but_attic_light
            shadow_color: color_gray
            shadow_spread: 2
            shadow_width: 20
        - lvgl.label.update:
            id: id_lv_lab_attic_light
            text_color: color_gray

  # Water Softener Salt Level Critical from HA #
  - platform: homeassistant
    id: id_ha_salt_lvl_crit
    entity_id: binary_sensor.esphome_web_9cd79a_sel_bas
    trigger_on_initial_state: True
    on_press:
      then:
        - lvgl.widget.update: 
            id: id_lv_but_salt_lvl
            hidden: false
    on_release:
      then:
        - lvgl.widget.update: 
            id: id_lv_but_salt_lvl
            hidden: true

  # Irrigation System Active from HA #
  - platform: homeassistant
    id: id_ha_watering_active
    entity_id: binary_sensor.rain_bird_irrigation_actif
    trigger_on_initial_state: True
    on_press:
      then:
        - lvgl.widget.update: 
            id: id_lv_but_watering_active
            hidden: false
    on_release:
      then:
        - lvgl.widget.update: 
            id: id_lv_but_watering_active
            hidden: true

  # Trash bin #
  - platform: homeassistant
    id: id_ha_trash_day
    entity_id: ${trash_bin_day_entity_id}
    trigger_on_initial_state: True
    on_press:
      then:
        - lvgl.widget.show: id_lv_but_variable_bin
        - lvgl.label.update:
            id: id_lv_lab_variable_bin
            text_color: color_red
            hidden: false
    on_release:
      then:
        - lvgl.widget.hide: id_lv_but_variable_bin
        - lvgl.widget.hide: id_lv_lab_variable_bin

  # Trash bin alert
  - platform: homeassistant
    id: id_ha_trash_alert
    entity_id: ${trash_bin_location_alert_entity_id}
    trigger_on_initial_state: True
    on_release:
      then:
        - lvgl.label.update:
            id: id_lv_lab_variable_bin
            text_color: color_red
        - if:
            condition:
              - binary_sensor.is_on: id_ha_trash_day
            then:
              - lvgl.widget.show: id_lv_but_variable_bin
              - lvgl.widget.show: id_lv_lab_variable_bin

  # Recycle bin #
  - platform: homeassistant
    id: id_ha_recycle_day
    entity_id: ${recycle_bin_day_entity_id}
    trigger_on_initial_state: True
    on_press:
      then:
        - lvgl.widget.show: id_lv_but_variable_bin
        - lvgl.label.update:
            id: id_lv_lab_variable_bin
            text_color: color_dark_green
            hidden: false
    on_release:
      then:
        - lvgl.widget.hide: id_lv_but_variable_bin
        - lvgl.widget.hide: id_lv_lab_variable_bin

  # Recycle bin alert
  - platform: homeassistant
    id: id_ha_recycle_alert
    entity_id: ${recycle_bin_location_alert_entity_id}
    trigger_on_initial_state: True
    on_release:
      then:
        - lvgl.label.update:
            id: id_lv_lab_variable_bin
            text_color: color_dark_green
        - if:
            condition:
              - binary_sensor.is_on: id_ha_recycle_day
            then:
              - lvgl.widget.show: id_lv_but_variable_bin
              - lvgl.widget.show: id_lv_lab_variable_bin

  # Compost bin #
  - platform: homeassistant
    id: id_ha_compost_day
    entity_id: ${compost_bin_day_entity_id}
    trigger_on_initial_state: True
    on_press:
      then:
        - lvgl.widget.show: id_lv_but_variable_bin
        - lvgl.label.update:
            id: id_lv_lab_variable_bin
            text_color: color_brown
            hidden: false
    on_release:
      then:
        - lvgl.widget.hide: id_lv_but_variable_bin
        - lvgl.widget.hide: id_lv_lab_variable_bin

  # Compost bin alert
  - platform: homeassistant
    id: id_ha_compost_alert
    entity_id: ${compost_bin_location_alert_entity_id}
    trigger_on_initial_state: True
    on_release:
      then:
        - lvgl.label.update:
            id: id_lv_lab_variable_bin
            text_color: color_brown
        - if:
            condition:
              - binary_sensor.is_on: id_ha_compost_day
            then:
              - lvgl.widget.show: id_lv_but_variable_bin
              - lvgl.widget.show: id_lv_lab_variable_bin

globals:
  - id: id_blinker_toggle
    type: bool
    restore_value: no
    initial_value: "false"
  - id: id_bin_blinker_toggle
    type: bool
    restore_value: no
    initial_value: 'false'

interval:
  - interval: 800ms
    startup_delay: 50s
    then:
      # Défi Hilo blinking
      - if:
          condition:
            - lambda: "return id(id_blinker_toggle) == false;"
          then:
            - lvgl.label.update: 
                id: id_lv_lab_defi_hilo
                text_color: color_yellow
            - globals.set:
                id: id_blinker_toggle
                value: "true"
          else:
            - lvgl.label.update: 
                id: id_lv_lab_defi_hilo
                text_color: color_dark_gray
            - globals.set:
                id: id_blinker_toggle
                value: "false"
      # Trash bin blinking
      - if:
          condition:
            and:
              - binary_sensor.is_on: id_ha_trash_alert
              - binary_sensor.is_on: id_ha_trash_day
          then:
            - if:
                condition:
                  - lambda: "return id(id_bin_blinker_toggle) == true;"
                then:
                  - lvgl.label.update:
                      id: id_lv_lab_variable_bin
                      text_color: color_red
                  - globals.set:
                      id: id_bin_blinker_toggle
                      value: "false"
                else:
                  - lvgl.label.update:
                      id: id_lv_lab_variable_bin
                      text_color: color_dark_gray
                  - globals.set:
                      id: id_bin_blinker_toggle
                      value: "true"
      # Recycle bin blinking
      - if:
          condition:
            and:
              - binary_sensor.is_on: id_ha_recycle_alert
              - binary_sensor.is_on: id_ha_recycle_day
          then:
            - if:
                condition:
                  - lambda: "return id(id_bin_blinker_toggle) == true;"
                then:
                  - lvgl.label.update:
                      id: id_lv_lab_variable_bin
                      text_color: color_dark_green
                  - globals.set:
                      id: id_bin_blinker_toggle
                      value: "false"
                else:
                  - lvgl.label.update:
                      id: id_lv_lab_variable_bin
                      text_color: color_dark_gray
                  - globals.set:
                      id: id_bin_blinker_toggle
                      value: "true"
      # Compost bin blinking
      - if:
          condition:
            and:
              - binary_sensor.is_on: id_ha_compost_alert
              - binary_sensor.is_on: id_ha_compost_day
          then:
            - if:
                condition:
                  - lambda: "return id(id_bin_blinker_toggle) == true;"
                then:
                  - lvgl.label.update:
                      id: id_lv_lab_variable_bin
                      text_color: color_brown
                  - globals.set:
                      id: id_bin_blinker_toggle
                      value: "false"
                else:
                  - lvgl.label.update:
                      id: id_lv_lab_variable_bin
                      text_color: color_dark_gray
                  - globals.set:
                      id: id_bin_blinker_toggle
                      value: "true"